version: 2
jobs:
  build:
    machine:
      pre:
        - sudo apt-get install texlive-xetex texinfo
    steps:
      - checkout
      - run:
          name: Install Texlive and TeXInfo
          command: 'sudo apt update && sudo apt install texlive texlive-xetex texlive-fonts-extra texlive-latex-extra texlive-plain-extra texinfo'
      - run: make info pdf

      - store_artifacts:
          path: /tmp/artifacts
